# The wiz-dev-app service provides a load-balancing proxy over the wiz-dev-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: wiz-dev-app
spec:
  type: LoadBalancer
  selector:
    app: wiz-dev-app
  ports:
  - port: 80
    targetPort: 8080