---
apiVersion: v1
kind: Namespace
metadata:
  name: game-dev-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-dev-app
  name: deployment-game-dev-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: game-dev-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-dev-app
    spec:
      containers:
      - image: blackicebird/2048
        imagePullPolicy: Always
        name: game-dev-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-dev-app
  name: game-dev-app-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: game-dev-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-dev-app
  name: game-dev-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # For each `listen-ports` object defined an ALB lister is created
    # For each listener created the rules defined in `spec` apply with some basic caveats
    # SSL redirect rule is applied only to the HTTP listener.  Cognito authentication rule
    # is applied to the HTTPS listener
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # Detailed redirect settings
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:341320276178:certificate/ce079edc-dc11-47f4-8fa3-88c85d63135b
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:341320276178:certificate/ce079edc-dc11-47f4-8fa3-88c85d63135b
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-port: '80'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/success-codes: 200-399
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: game-dev-app-service
              port:
                number: 80